WebSipicha/WebSipicha/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSipicha.Models;

namespace WebSipicha.Controllers
{

    public class PurchasesController : Controller
    {
        private ModelContext db = new ModelContext();

        // GET: Purchases
        public async Task<ActionResult> Index()
        {
            var purchaseSet = db.PurchaseSet.Include(p => p.Shop);
            return View(await purchaseSet.ToListAsync());
        }

        // GET: Purchases/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Purchase purchase = await db.PurchaseSet.Include(p => p.Shop).Where(p => p.Id == id).FirstOrDefaultAsync();
            if (purchase == null)
            {
                return HttpNotFound();
            }
            return View(purchase);
        }

        // GET: Purchases/Create
        public ActionResult Create()
        {
            ViewBag.ShopId = new SelectList(db.ShopSet.Where(s => !s.IsClosed), "Id", "Name");
            ViewBag.TeaId = new SelectList(db.TeaSet, "Id", "Name");
            ViewBag.Season = new SelectList(new string[] { "Весна", "Лето", "Осень", "Зима" });
            return View();
        }

        // POST: Purchases/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Готово")]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,Cost,ShopId")] Purchase purchase,
            [Bind(Include = "Id,Province,Season,Year,TeaId")]Picking picking)
        {
            if (purchase.Cost == null)
            {
                purchase.Cost = 0;
            }
            if (ModelState.IsValid)
            {
                var fromBasePick = db.PickingSet.Where(p => p.TeaId == picking.TeaId)
                    .FirstOrDefault(p => p.Province == picking.Province && p.Season == picking.Season && p.Year == picking.Year);
                int? fromBasePickingId = null;
                if (fromBasePick == null)
                {
                    db.PickingSet.Add(picking);
                    await db.SaveChangesAsync();
                }
                else
                {
                    fromBasePickingId = fromBasePick.Id;
                }

                purchase.Person = "Пользователь";
                purchase.PickingId = fromBasePickingId == null ? picking.Id : fromBasePickingId;
                db.PurchaseSet.Add(purchase);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ShopId = new SelectList(db.ShopSet.Where(s => !s.IsClosed), "Id", "Name");
            ViewBag.TeaId = new SelectList(db.TeaSet, "Id", "Name");
            ViewBag.Season = new SelectList(new string[] { "Весна", "Лето", "Осень", "Зима" });
            return View(purchase);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultiButton(MatchFormKey = "shopAction", MatchFormValue = "Сохранить")]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,Name,Address,WebSite")] Shop shop,
            [Bind(Include = "Cost")] Purchase purchase,
            [Bind(Include = "Province,Season,Year,TeaId")]Picking picking)
        {
            if (ModelState.IsValid)
            {
                db.ShopSet.Add(shop);
                await db.SaveChangesAsync();
            }
            ViewBag.ShopId = new SelectList(db.ShopSet.Where(s => !s.IsClosed), "Id", "Name", shop.Id);
            ViewBag.TeaId = new SelectList(db.TeaSet, "Id", "Name", picking.TeaId);
            ViewBag.Season = new SelectList(new string[] { "Весна", "Лето", "Осень", "Зима" }, picking.Season);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultiButton(MatchFormKey = "teaAction", MatchFormValue = "Сохранить")]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,Name,Category")] Tea tea,
            [Bind(Include = "Cost,ShopId")] Purchase purchase,
            [Bind(Include = "Province,Season,Year")]Picking picking)
        {
            if (ModelState.IsValid)
            {
                db.TeaSet.Add(tea);
                await db.SaveChangesAsync();
            }
            ViewBag.ShopId = new SelectList(db.ShopSet.Where(s => !s.IsClosed), "Id", "Name", purchase.ShopId);
            ViewBag.TeaId = new SelectList(db.TeaSet, "Id", "Name", tea.Id);
            ViewBag.Season = new SelectList(new string[] { "Весна", "Лето", "Осень", "Зима" }, picking.Season);
            return View();
        }

        // GET: Purchases/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Purchase purchase = await db.PurchaseSet.FindAsync(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            ViewBag.PickingId = new SelectList(db.PickingSet, "Id", "Tea", purchase.PickingId);
            ViewBag.ShopId = new SelectList(db.ShopSet, "Id", "Name", purchase.ShopId);
            return View(purchase);
        }

        // POST: Purchases/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Person,Cost,ShopId,PickingId")] Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchase).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PickingId = new SelectList(db.PickingSet, "Id", "Tea", purchase.PickingId);
            ViewBag.ShopId = new SelectList(db.ShopSet, "Id", "Name", purchase.ShopId);
            return View(purchase);
        }

        // GET: Purchases/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Purchase purchase = await db.PurchaseSet.Include(p => p.Shop).Where(p => p.Id == id).FirstOrDefaultAsync();
            if (purchase == null)
            {
                return HttpNotFound();
            }
            return View(purchase);
        }

        // POST: Purchases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Purchase purchase = await db.PurchaseSet.FindAsync(id);
            db.PurchaseSet.Remove(purchase);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {

            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebSipicha/WebSipicha/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSipicha.Models;

namespace WebSipicha.Controllers
{
    public class ShopsController : Controller
    {
        private ModelContext db = new ModelContext();

        // GET: Shops
        public async Task<ActionResult> Index()
        {
            return View(await db.ShopSet.ToListAsync());
        }

        // GET: Shops/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = await db.ShopSet.FindAsync(id);
            if (shop == null)
            {
                return HttpNotFound();
            }
            return View(shop);
        }

        public ActionResult ShopInput()
        {
            return PartialView();
        }

        // GET: Shops/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shops/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Address,WebSite")] Shop shop)
        {
            if (ModelState.IsValid)
            {
                db.ShopSet.Add(shop);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(shop);
        }

        // GET: Shops/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = await db.ShopSet.FindAsync(id);
            if (shop == null)
            {
                return HttpNotFound();
            }
            return View(shop);
        }

        // POST: Shops/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Address,WebSite")] Shop shop)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shop).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(shop);
        }

        // GET: Shops/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shop shop = await db.ShopSet.Include(s => s.PurchaseSet).FirstOrDefaultAsync(s => s.Id == id);

            if (shop == null)
            {
                return HttpNotFound();
            }
            return View(shop);
        }

        // POST: Shops/Delete/5
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Удалить")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Shop shop = await db.ShopSet.FindAsync(id);
            db.ShopSet.Remove(shop);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Shops/Delete/5
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Архивировать")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ArchiveConfirmed(int id)
        {
            Shop shop = await db.ShopSet.FindAsync(id);
            shop.IsClosed = true;
            db.Entry(shop).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Shops/Delete/5
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Разархивировать")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UnArchiveConfirmed(int id)
        {
            Shop shop = await db.ShopSet.FindAsync(id);
            shop.IsClosed = false;
            db.Entry(shop).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebSipicha/WebSipicha/Controllers/TeasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSipicha.Models;

namespace WebSipicha.Controllers
{
    public class TeasController : Controller
    {
        private ModelContext db = new ModelContext();

        // GET: Teas
        public async Task<ActionResult> Index()
        {
            return View(await db.TeaSet.ToListAsync());
        }

        // GET: Teas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tea tea = await db.TeaSet.FindAsync(id);
            if (tea == null)
            {
                return HttpNotFound();
            }
            return View(tea);
        }

        public ActionResult TeaInput()
        {
            return PartialView();
        }

        // GET: Teas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Teas/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Category")] Tea tea)
        {
            if (ModelState.IsValid)
            {
                db.TeaSet.Add(tea);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(tea);
        }

        // GET: Teas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tea tea = await db.TeaSet.FindAsync(id);
            if (tea == null)
            {
                return HttpNotFound();
            }
            return View(tea);
        }

        // POST: Teas/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Category")] Tea tea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tea).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(tea);
        }

        // GET: Teas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tea tea = await db.TeaSet.Include(p => p.PickingSet).FirstOrDefaultAsync(p => p.Id == id);
            if (tea == null)
            {
                return HttpNotFound();
            }
            return View(tea);
        }

        // POST: Teas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Tea tea = await db.TeaSet.FindAsync(id);
            db.TeaSet.Remove(tea);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebSipicha/WebSipicha/Views/Purchases/Create.cshtml
@model WebSipicha.Models.Purchase

@{
    ViewBag.Title = "Добавить покупку";
}

<h2>Добавть</h2>

@using (Html.BeginForm("Create", "Purchases", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Purchase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control", @placeholder = "0.0" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Shop, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopId, "", new { @class = "text-danger" })
                <div id="partialShop">
                    @Ajax.ActionLink("Добавить новый магазин", "ShopInput", "Shops", new AjaxOptions { UpdateTargetId = "partialShop" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picking.Tea, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Picking.Tea, "", new { @class = "text-danger" })
                <div id="partialTea">
                    @Ajax.ActionLink("Добавить новый чай", "TeaInput", "Teas", new AjaxOptions { UpdateTargetId = "partialTea" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picking.Province, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("Province", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picking.Province, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picking.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("Year", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picking.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picking.Season, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Season", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Picking.Season, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="action" value="Готово" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @Scripts.Render("~/scripts/jquery.validate.min.js")
}

WebSipicha/WebSipicha/Views/Purchases/Delete.cshtml
@model WebSipicha.Models.Purchase

@{
    ViewBag.Title = "Удалить запись о покупке";
}

<h2>Удалить запись о покупке</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Picking.Tea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picking.Tea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shop.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

WebSipicha/WebSipicha/Views/Purchases/Details.cshtml
@model WebSipicha.Models.Purchase

@{
    ViewBag.Title = "Детали";
}

<h2>Детали</h2>

<div>
    <h4>Ваши покупки</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Picking.Tea.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picking.Tea.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Picking.Province)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picking.Province)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shop.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад к списку", "Index")
</p>

WebSipicha/WebSipicha/Views/Purchases/Edit.cshtml
@model WebSipicha.Models.Purchase

@{
    ViewBag.Title = "Изменить";
}

<h2>Изменить</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Информация о покупке</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Person, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopId, "ShopId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebSipicha/WebSipicha/Views/Purchases/Index.cshtml
@model IEnumerable<WebSipicha.Models.Purchase>

@{
    ViewBag.Title = "Информация о покупках";
}

<h2>Ваши покупки</h2>

<p>
    @Html.ActionLink("Добавить", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Picking.Tea)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picking.Province)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Shop)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Person)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Picking.Tea.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Picking.Province)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Shop.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Person)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Детали", "Details", new { id = item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>